security:
  
  firewalls:
    main:
      pattern: ^/
      anonymous: ~
      form_login: ~
  
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
      
  providers:
    main:
      
  access_control: ~  